const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { includeStatementForPart, installProjectParts } = require("../../src/app");
const { writeProjectConfig, findProjectConfigInDirectory } = require("../../src/project");
const { lockPathFor } = require("../../src/bom");

test("installProjectParts installs manifest parts and updates stored MPNs", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "schrune-cli-parts-"));
    fs.writeFileSync(path.join(dir, "main.schrune"), "module top () {}\n");
    writeProjectConfig(path.join(dir, "schrune.json"), {
        name: "Demo",
        entry: "./main.schrune",
        parts: [{ MPN: "OLD_NAME", LCSC: "C1234" }],
    });

    const calls = [];
    const progress = [];
    try {
        const installed = await installProjectParts(findProjectConfigInDirectory(dir), {
            onProgress(entry) {
                progress.push(entry);
            },
            addLcscPart: async (lcsc, options) => {
                calls.push({ lcsc, options });
                return {
                    lcsc,
                    partName: "NEW_NAME",
                    directory: path.join(dir, "parts", "NEW_NAME"),
                    schrunePath: path.join(dir, "parts", "NEW_NAME", "NEW_NAME.schrune"),
                    pins: [],
                    modelDownloaded: false,
                };
            },
        });

        assert.equal(installed.length, 1);
        assert.equal(calls.length, 1);
        assert.equal(calls[0].lcsc, "C1234");
        assert.equal(calls[0].options.updateExistingSchrune, undefined);
        assert.equal(calls[0].options.partsDir, path.join(dir, "parts"));
        assert.deepEqual(progress.map(({ current, total }) => ({ current, total })), [
            { current: 0, total: 1 },
            { current: 1, total: 1 },
        ]);

        const project = findProjectConfigInDirectory(dir);
        assert.deepEqual(project.config.parts, [{ MPN: "NEW_NAME", LCSC: "C1234" }]);
    } finally {
        fs.rmSync(dir, { recursive: true, force: true });
    }
});

test("installProjectParts can include autogenerated lock parts and pass update mode", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "schrune-cli-parts-auto-"));
    const entryPath = path.join(dir, "main.schrune");
    fs.writeFileSync(entryPath, "module top () {}\n");
    writeProjectConfig(path.join(dir, "schrune.json"), {
        name: "Demo",
        entry: "./main.schrune",
        parts: [],
    });
    fs.mkdirSync(path.dirname(lockPathFor(entryPath)), { recursive: true });
    fs.writeFileSync(lockPathFor(entryPath), `${JSON.stringify({
        version: 1,
        parts: [{ lcsc: "C1525", partName: "AUTO_PART" }],
        selectors: {},
        selectionCache: {},
    }, null, 2)}\n`);

    const calls = [];
    const progress = [];
    try {
        const installed = await installProjectParts(findProjectConfigInDirectory(dir), {
            includeAutogenerated: true,
            update: true,
            onProgress(entry) {
                progress.push(entry);
            },
            addLcscPart: async (lcsc, options) => {
                calls.push({ lcsc, options });
                return {
                    lcsc,
                    partName: "AUTO_PART",
                    directory: path.join(dir, "parts", "autogenerated", "AUTO_PART"),
                    schrunePath: path.join(dir, "parts", "autogenerated", "AUTO_PART", "AUTO_PART.schrune"),
                    pins: [],
                    modelDownloaded: true,
                };
            },
        });

        assert.equal(installed.length, 1);
        assert.equal(calls.length, 1);
        assert.equal(calls[0].lcsc, "C1525");
        assert.equal(calls[0].options.updateExistingSchrune, true);
        assert.equal(calls[0].options.partsDir, path.join(dir, "parts", "autogenerated"));
        assert.deepEqual(progress.map(({ current, total }) => ({ current, total })), [
            { current: 0, total: 1 },
            { current: 1, total: 1 },
        ]);
    } finally {
        fs.rmSync(dir, { recursive: true, force: true });
    }
});

test("includeStatementForPart prints a normalized relative include", () => {
    const statement = includeStatementForPart(
        "/tmp/demo",
        "/tmp/demo/parts/RP2040/RP2040.schrune"
    );

    assert.equal(statement, '#include "parts/RP2040/RP2040.schrune"');
});
