const fs = require("fs");
const path = require("path");
const { addLcscPart } = require("./lcsc");
const { searchJlcParts, selectBestJlcPart } = require("./jlc");

const GENERIC_TYPES = new Set(["Resistor", "Capacitor", "Inductor", "Diode"]);
const LOCK_VERSION = 1;

function designatorPrefix(component) {
    return component.info && component.info.designatorPrefix
        ? component.info.designatorPrefix
        : "U";
}

function pinNetList(component) {
    return component.pins
        .filter(Boolean)
        .map((pin) => pin.net || "")
        .sort();
}

function componentKind(component) {
    return component.constructor && component.constructor.name || "Component";
}

function componentSignature(component) {
    return JSON.stringify({
        type: componentKind(component),
        value: component.value,
        footprint: component.footprint || component.info && component.info.footprint,
        voltage: component.voltage,
        power: component.power,
        tolerance: component.tolerance,
        nets: pinNetList(component),
    });
}

function assignDesignators(stepResult, lock = {}) {
    const usedByPrefix = new Map();

    const components = stepResult.components.map((component, index) => {
        const signature = componentSignature(component);
        component.__schrune = {
            ...(component.__schrune || {}),
            index,
            signature,
        };
        return component;
    });

    components.sort((left, right) => {
        const leftKey = `${designatorPrefix(left)}\0${left.__schrune.signature}\0${left.__schrune.index}`;
        const rightKey = `${designatorPrefix(right)}\0${right.__schrune.signature}\0${right.__schrune.index}`;
        return leftKey.localeCompare(rightKey);
    });

    for (const component of components) {
        const prefix = designatorPrefix(component);
        if (!usedByPrefix.has(prefix)) {
            usedByPrefix.set(prefix, new Set());
        }
        const used = usedByPrefix.get(prefix);
        let number = 1;
        while (used.has(number)) {
            number++;
        }
        used.add(number);
        component.designator = `${prefix}${number}`;
    }

    return {
        ...stepResult,
        components: components.sort((left, right) => left.__schrune.index - right.__schrune.index),
    };
}

function lockPathFor(filePath) {
    return path.join(path.dirname(filePath), "parts", "autogenerated", "parts-lock.json");
}

function readPartsLock(filePath) {
    const lockPath = lockPathFor(filePath);
    if (!fs.existsSync(lockPath)) {
        return { version: LOCK_VERSION, parts: [], selectors: {} };
    }
    return JSON.parse(fs.readFileSync(lockPath, "utf8"));
}

function writePartsLock(filePath, lock) {
    const lockPath = lockPathFor(filePath);
    fs.mkdirSync(path.dirname(lockPath), { recursive: true });
    fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

function isGenericComponent(component) {
    return GENERIC_TYPES.has(componentKind(component));
}

function componentFilters(component) {
    return {
        type: componentKind(component),
        value: component.value,
        footprint: component.footprint || undefined,
        voltage: component.voltage || component.maxVoltage,
        power: component.power || component.maxPower,
        tolerance: component.tolerance,
    };
}

function normalizeLock(lock) {
    const parts = [];
    const selectors = { ...(lock.selectors || {}) };

    if (Array.isArray(lock.parts)) {
        for (const part of lock.parts) {
            const normalized = normalizeSelectedPart(part);
            if (normalized && normalized.lcsc) {
                parts.push(normalized);
            }
        }
    }

    // Backward compatibility for the previous verbose lock shape.
    for (const entry of Array.isArray(lock.parts) ? lock.parts : []) {
        if (entry && entry.part) {
            const normalized = normalizeSelectedPart(entry.part);
            if (normalized && normalized.lcsc) {
                parts.push(normalized);
                for (const designator of entry.designators || [entry.designator]) {
                    if (designator && !selectors[designator]) {
                        selectors[designator] = normalized.lcsc;
                    }
                }
            }
        }
    }

    return {
        version: LOCK_VERSION,
        parts: uniqueParts(parts),
        selectors,
    };
}

function valueSearchTerm(component) {
    const type = componentKind(component).toLowerCase();
    return [component.value, component.footprint, type]
        .filter(Boolean)
        .join(" ");
}

function normalizeSelectedPart(part) {
    if (!part) {
        return undefined;
    }
    return {
        lcsc: String(part.lcsc || part.LCSC || "").toUpperCase(),
        manufacturer: part.manufacturer || part.manufacture,
        mpn: part.mpn || part.partNumber,
        package: part.package || part.footprint,
        description: part.description,
        datasheetUrl: part.datasheetUrl || part.datasheet_url,
        stock: part.stock,
        unitCost: part.unitCost ?? part.unit_cost,
        isBasic: part.isBasic ?? part.is_basic,
        isPreferred: part.isPreferred ?? part.is_preferred,
    };
}

function uniqueParts(parts) {
    const byLcsc = new Map();
    for (const part of parts) {
        const normalized = normalizeSelectedPart(part);
        if (normalized && normalized.lcsc) {
            byLcsc.set(normalized.lcsc, {
                ...(byLcsc.get(normalized.lcsc) || {}),
                ...normalized,
            });
        }
    }
    return [...byLcsc.values()].sort((left, right) => left.lcsc.localeCompare(right.lcsc, undefined, { numeric: true }));
}

function findLockedPart(lock, component) {
    const normalizedLock = normalizeLock(lock);
    const lcsc = normalizedLock.selectors[component.designator];
    if (!lcsc) {
        return undefined;
    }
    return normalizedLock.parts.find((part) => part.lcsc === String(lcsc).toUpperCase()) || { lcsc };
}

function rankedParts(parts) {
    const remaining = [...parts].map(normalizeSelectedPart).filter((part) => part && part.lcsc);
    const ranked = [];

    while (remaining.length) {
        const selected = selectBestJlcPart(remaining);
        ranked.push(selected);
        remaining.splice(remaining.findIndex((part) => part.lcsc === selected.lcsc), 1);
    }

    return ranked;
}

function importedAssetsExist(importResult) {
    if (!importResult || !importResult.directory || !importResult.partName) {
        return false;
    }

    return fs.existsSync(path.join(importResult.directory, `${importResult.partName}.kicad_sym`))
        && fs.existsSync(path.join(importResult.directory, `${importResult.partName}.kicad_mod`));
}

async function importSelectedPart(part, filePath, partsDir, options) {
    if (options.downloadParts === false) {
        return { ok: true };
    }

    const importer = options.addLcscPart || addLcscPart;
    const result = await importer(part.lcsc, {
        cwd: path.dirname(filePath),
        partsDir,
        fetch: options.fetch,
    });

    return {
        ok: importedAssetsExist(result),
        result,
    };
}

async function autoSelectionCandidates(component, options) {
    if (options.selectParts) {
        return (await options.selectParts(component, componentFilters(component))).map(normalizeSelectedPart);
    }

    if (options.selectPart) {
        const selected = await options.selectPart(component, componentFilters(component));
        return Array.isArray(selected) ? selected.map(normalizeSelectedPart) : [normalizeSelectedPart(selected)];
    }

    const parts = await searchJlcParts(valueSearchTerm(component), {
        fetch: options.fetch,
        limit: 50,
    });
    return rankedParts(parts);
}

function initialSelectionCandidates(component, lock, noPartsLock) {
    if (component.info && component.info.LCSC) {
        return {
            explicit: true,
            parts: [normalizeSelectedPart({
                lcsc: component.info.LCSC,
                manufacturer: component.info.manufacture,
                mpn: component.info.partNumber,
                package: component.info.footprint || component.footprint,
            })],
        };
    }

    const lockedPart = noPartsLock ? undefined : findLockedPart(lock, component);
    return {
        explicit: false,
        parts: lockedPart ? [normalizeSelectedPart(lockedPart)] : [],
    };
}

function applyPartToComponent(component, part) {
    if (!part) {
        return;
    }
    component.selectedPart = part;
    component.info = {
        ...component.info,
        partNumber: part.mpn || component.info.partNumber,
        manufacture: part.manufacturer || component.info.manufacture,
        footprint: part.package || component.info.footprint,
        LCSC: part.lcsc || component.info.LCSC,
    };
}

async function resolveGenericParts(filePath, compiled, options = {}) {
    const noPartsLock = Boolean(options.noPartsLock);
    const lock = noPartsLock ? { version: LOCK_VERSION, parts: [], selectors: {} } : normalizeLock(readPartsLock(filePath));
    const selectedParts = [...lock.parts];
    const selectors = {};
    const partsDir = path.join(path.dirname(filePath), "parts", "autogenerated");
    const genericComponents = compiled.components.filter(isGenericComponent);
    options.onProgress && options.onProgress({ current: 0, total: genericComponents.length });

    for (let index = 0; index < genericComponents.length; index++) {
        const component = genericComponents[index];
        options.onProgress && options.onProgress({ current: index, total: genericComponents.length, component });

        const candidates = initialSelectionCandidates(component, lock, noPartsLock);
        let selectedPart;
        const importErrors = [];
        async function tryCandidates(parts) {
            for (const candidate of parts) {
                if (!candidate || !candidate.lcsc) {
                    continue;
                }

                const imported = await importSelectedPart(candidate, filePath, partsDir, options);
                if (imported.ok) {
                    return candidate;
                }

                importErrors.push(`${candidate.lcsc} did not provide KiCad symbol and footprint assets`);
                if (candidates.explicit) {
                    break;
                }
            }
            return undefined;
        }

        selectedPart = await tryCandidates(candidates.parts);
        if (!selectedPart && !candidates.explicit) {
            const fallbackParts = await autoSelectionCandidates(component, options);
            const tried = new Set(candidates.parts.map((part) => part && part.lcsc).filter(Boolean));
            selectedPart = await tryCandidates(uniqueParts(fallbackParts).filter((part) => !tried.has(part.lcsc)));
        }

        if (!selectedPart) {
            const detail = importErrors.length ? ` (${importErrors.join("; ")})` : "";
            throw new Error(`Could not select a JLC/LCSC part for ${component.designator}${detail}`);
        }

        applyPartToComponent(component, selectedPart);
        selectedParts.push(selectedPart);
        selectors[component.designator] = selectedPart.lcsc;
        options.onProgress && options.onProgress({ current: index + 1, total: genericComponents.length, component });
    }

    const nextLock = {
        version: LOCK_VERSION,
        parts: uniqueParts(selectedParts),
        selectors: Object.fromEntries(
            Object.entries(selectors).sort(([left], [right]) => left.localeCompare(right, undefined, { numeric: true }))
        ),
    };
    if (!noPartsLock) {
        writePartsLock(filePath, nextLock);
    }

    return {
        ...compiled,
        partsLock: nextLock,
    };
}

function bomIdentity(component) {
    const selected = component.selectedPart || {};
    return [
        selected.lcsc || component.info && component.info.LCSC || "",
        selected.mpn || component.info && component.info.partNumber || componentKind(component),
        component.value || "",
        component.footprint || component.info && component.info.footprint || "",
    ].join("\0");
}

function makeBomRows(compiled) {
    const groups = new Map();

    for (const component of compiled.components) {
        const key = bomIdentity(component);
        if (!groups.has(key)) {
            const selected = component.selectedPart || {};
            groups.set(key, {
                designators: [],
                quantity: 0,
                manufacturer: selected.manufacturer || component.info && component.info.manufacture || "",
                mpn: selected.mpn || component.info && component.info.partNumber || "",
                lcsc: selected.lcsc || component.info && component.info.LCSC || "",
                value: component.value || "",
                footprint: selected.package || component.footprint || component.info && component.info.footprint || "",
                type: componentKind(component),
                description: selected.description || "",
                stock: selected.stock ?? "",
                unitCost: selected.unitCost ?? "",
                isBasic: selected.isBasic ?? "",
                isPreferred: selected.isPreferred ?? "",
            });
        }

        const row = groups.get(key);
        row.quantity++;
        row.designators.push(component.designator);
    }

    return [...groups.values()].sort((left, right) => left.designators[0].localeCompare(right.designators[0], undefined, { numeric: true }));
}

function csvEscape(value) {
    const text = String(value ?? "");
    return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function bomCsv(rows) {
    const headers = [
        "Designator",
        "Quantity",
        "Manufacturer",
        "Manufacturer Part Number",
        "LCSC",
        "Value",
        "Footprint",
        "Type",
        "Description",
        "Stock",
        "Unit Cost",
        "Basic",
        "Preferred",
    ];
    const lines = [headers.join(",")];
    for (const row of rows) {
        lines.push([
            row.designators.join(" "),
            row.quantity,
            row.manufacturer,
            row.mpn,
            row.lcsc,
            row.value,
            row.footprint,
            row.type,
            row.description,
            row.stock,
            row.unitCost,
            row.isBasic,
            row.isPreferred,
        ].map(csvEscape).join(","));
    }
    return `${lines.join("\n")}\n`;
}

function writeBomCsv(filePath, rows) {
    const parsed = path.parse(filePath);
    const outputPath = path.join(parsed.dir, `${parsed.name}.BOM.csv`);
    fs.writeFileSync(outputPath, bomCsv(rows));
    return outputPath;
}

async function step3(filePath, compiled, options = {}) {
    const resolved = await resolveGenericParts(filePath, compiled, options);
    const bomRows = makeBomRows(resolved);
    const bomPath = writeBomCsv(filePath, bomRows);
    return {
        ...resolved,
        bomRows,
        bomPath,
    };
}

module.exports = {
    assignDesignators,
    bomCsv,
    componentFilters,
    componentSignature,
    lockPathFor,
    makeBomRows,
    readPartsLock,
    resolveGenericParts,
    step3,
    writeBomCsv,
};
